services:
  customer-db:
    image: postgres
    container_name: customer_db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data 