
version: '3.8'
services:
  customer_postgres:
    image: postgres
    restart: unless-stopped
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  redis-customer:
    image: redis:latest
    restart: always
    ports:
      - "6378:6378"
    volumes:
      - redis:/data
volumes:
  postgres:
    driver: local
  redis:
    driver: local

