
version: '3.8'
services:
  postgres_gateway:
    image: postgres
    restart: unless-stopped
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql
  redis_gateway:
    image: redis:latest
    restart: always
    command: redis-server --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"
    volumes:
      - redis:/data
    environment:
      # - REDIS_USER=hoangpc
      # - REDIS_PASSWORD=hoangpc
      - REDIS_PORT=6381
      - REDIS_DATABASES=2
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shoppe_v2_rmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file: ../.env
    networks:
      - shoppe_v2
volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  shoppe_v2:
    external: true
