export enum ErrorMessage {
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  WRONG_PASSWORD = 'WRONG_PASSWORD',

  CUSTOMER_NOT_EXIST = 'CUSTOMER_NOT_EXIST',
  CLIENT_PASSWORD_CHANGE_NOT_VALID = 'CLIENT_PASSWORD_CHANGE_NOT_VALID',
  CLIENT_LOCKED_OR_DELETED = 'CLIENT_LOCKED_OR_DELETED',
  CLIENT_CANCELED_OR_DELETED = 'CLIENT_CANCELED_OR_DELETED',

  USR_IS_EXISTED = 'EMAIL_OR_PHONE_IS_SIGNED_UP_TO_ANOTHER_ACCOUNT',
  USER_IS_TEMP_LOCK = 'USER_IS_TEMP_LOCK',

  OTP_EXPIRED = 'OTP_EXPIRED',
  MAX_OTP_ON_TIME = 'MAX_OTP_ON_TIME',
}
